const state={section:'vocab',level:'basic',mode:'all',search:'',questions:[],index:0,answered:0,correct:0,score:{}};
const sections={
  vocab:{title:'単語',description:'重要語をレベル別に確認。普通の常用語から共通テスト・二次・英検まで。',levels:[['basic','🟢 基礎'],['standard','🔵 標準'],['developed','🟡 発展'],['advanced','🟠 上級'],['hard','🔴 難関']]},
  idiom:{title:'熟語',description:'重要熟語・群動詞・語法的なまとまりを、意味と文脈の両方から確認。',levels:[['basic','基礎'],['standard','標準'],['entrance','入試'],['hard','発展']]},
  grammar:{title:'文法',description:'総文法の確認と、入試型の文法クイズへ。',levels:[['overview','3.1 総文法'],['quiz','3.2 文法クイズ']]},
  reading:{title:'長文',description:'通常長文・共通テスト型から始め、国公立二次・難関大へ拡張。',levels:[['normal','通常長文'],['common','共通テスト'],['national','国公立二次'],['hard','難関大']]}
};
const files={vocab:{basic:['data/vocab/basic-01.json'],standard:['data/vocab/standard-01.json'],developed:['data/vocab/developed-01.json'],advanced:['data/vocab/advanced-01.json'],hard:['data/vocab/hard-01.json']},idiom:{basic:['data/idioms/basic-01.json'],standard:['data/idioms/standard-01.json'],entrance:['data/idioms/entrance-01.json'],hard:['data/idioms/hard-01.json']},grammar:{overview:['data/grammar/overview-01.json'],quiz:['data/grammar/quiz-01.json']},reading:{normal:[],common:[],national:[],hard:[]}};
const $=id=>document.getElementById(id);
const key=q=>`${q.type}:${q.id}`;
function loadProgress(){try{state.score=JSON.parse(localStorage.getItem('eng-god-progress')||'{}')}catch{state.score={}}renderStats()}
function saveProgress(){localStorage.setItem('eng-god-progress',JSON.stringify(state.score));renderStats()}
function renderStats(){const vals=Object.values(state.score);const answered=vals.filter(v=>v.answered).length;const correct=vals.filter(v=>v.correct).length;$('answeredCount').textContent=answered;$('correctCount').textContent=correct;$('accuracy').textContent=answered?`${Math.round(correct/answered*100)}%`:'0%'}
function renderNav(){const nav=$('categoryNav');nav.innerHTML='';for(const [id,s] of Object.entries(sections)){const h=document.createElement('div');h.className='nav-section';h.textContent=id==='vocab'?'① 単語':id==='idiom'?'② 熟語':id==='grammar'?'③ 文法':'⑤ 長文';nav.append(h);const b=document.createElement('button');b.className=`nav-item ${state.section===id?'active':''}`;b.textContent=s.title;b.onclick=()=>{state.section=id;state.level=s.levels[0][0];resetQuestionArea();renderAll()};nav.append(b)}}
function renderAll(){renderNav();const s=sections[state.section];$('pageTitle').textContent=s.title;$('pageDescription').textContent=s.description;const tabs=$('levelTabs');tabs.innerHTML='';s.levels.forEach(([id,label])=>{const b=document.createElement('button');b.className=`level-btn ${state.level===id?'active':''}`;b.textContent=label;b.onclick=()=>{state.level=id;resetQuestionArea();renderAll()};tabs.append(b)});$('searchInput').value=state.search;$('modeSelect').value=state.mode;updateInfo()}
async function fetchData(){const urls=files[state.section]?.[state.level]||[];const pieces=await Promise.all(urls.map(u=>fetch(u).then(r=>r.ok?r.json():[])));state.questions=pieces.flat();filterQuestions();}
function filterQuestions(){let qs=[...state.questions];const q=state.search.trim().toLowerCase();if(q)qs=qs.filter(x=>`${x.word||''} ${x.meaning||''} ${x.ja||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q));if(state.mode==='weak')qs=qs.filter(x=>state.score[key(x)]?.wrong);if(state.mode==='unanswered')qs=qs.filter(x=>!state.score[key(x)]?.answered);state.filtered=qs;updateInfo()}
function updateInfo(){$('datasetInfo').textContent=`${state.section} / ${state.level}：${state.filtered?.length||0}問`}
function resetQuestionArea(){$('questionArea').classList.add('hidden');$('questionArea').innerHTML='';$('emptyState').style.display='block';state.questions=[];state.filtered=[]}
function startQuiz(){if(!state.filtered?.length){$('emptyState').style.display='block';$('emptyState').querySelector('h2').textContent=state.section==='reading'?'長文データは準備中です':'該当する問題がありません';return}state.questions=[...state.filtered].sort(()=>Math.random()-.5);state.index=0;$('emptyState').style.display='none';showQuestion()}
function showQuestion(){const q=state.questions[state.index];if(!q)return;const area=$('questionArea');area.classList.remove('hidden');const choices=[...q.choices].sort(()=>Math.random()-.5);area.innerHTML=`<div class="q-meta"><span class="tag">${q.level||state.level}</span><span>${state.index+1} / ${state.questions.length}</span></div><div class="question">${escapeHtml(q.question)}<small>${escapeHtml(q.prompt||'')}</small></div><div class="answers" id="answers"></div><div id="explain"></div><div class="next-row"><button id="nextBtn" class="primary-btn" style="display:none">次の問題</button></div>`;const box=$('answers');choices.forEach((c,i)=>{const b=document.createElement('button');b.className='answer-btn';b.textContent=c.text;b.onclick=()=>answer(q,c.correct, b);box.append(b)});$('nextBtn').onclick=()=>{state.index++;showQuestion()}}
function answer(q,isCorrect,btn){const k=key(q);const rec=state.score[k]||{answered:0,correct:0,wrong:0};rec.answered+=1;if(isCorrect){rec.correct+=1;btn.classList.add('correct')}else{rec.wrong+=1;btn.classList.add('wrong')}state.score[k]=rec;document.querySelectorAll('.answer-btn').forEach(b=>b.disabled=true);if(!isCorrect){document.querySelectorAll('.answer-btn').forEach(b=>{if(b.textContent===q.answer)b.classList.add('correct')})}$('explain').innerHTML=`<div class="explanation"><strong>${isCorrect?'正解！':'不正解'}</strong><br>${escapeHtml(q.explanation||'この問題のポイントを確認しましょう。')}</div>`;$('nextBtn').style.display='inline-block';saveProgress()}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('startBtn').onclick=startQuiz;$('shuffleBtn').onclick=()=>{state.mode='all';state.search='';state.section='vocab';state.level='basic';loadAndStart()};$('searchInput').oninput=async e=>{state.search=e.target.value;filterQuestions()};$('modeSelect').onchange=e=>{state.mode=e.target.value;filterQuestions()};$('resetProgress').onclick=()=>{if(confirm('学習進捗をすべて削除します。よろしいですか？')){state.score={};saveProgress()}};
async function loadAndStart(){renderAll();await fetchData();startQuiz()}
(async()=>{loadProgress();renderAll();await fetchData()})();
